### ISSUE TITLE
exception inside the event bus handler can not be caught by vaadin application

### ISSUE THREAD

**Issue by Neway6655** [panterch/org.vaadin.mvp#7]
Hello, I met a problem that vaadin application can't catch the exception happened in the event bus handler, so the application is hard to have a common method to handle the exception happened inside the handler, I saw that EventBusHandler will catch the exception thrown by the handler and won't throw out but just log the error.

So if we want to let user know that there are some errors happened when doing some operation, the only way to do this is to add try catch for each handler's invoke method, such as:

public void onGotoSearchPage() {
            try {
                                ...
                loadInitData();   // if exception thrown here.
                                ...
                                view.showSearchPage();
            } catch (Exception e) {
                view.showOperationFailedWindow(getErrorMsg(e));
            } 
        }
    }

just like the example above, onGotoSearchPage() is the gotoSearchPage event's handle method, if exception thrown when loadInitData(), and we need to add try catch around it to handler the exception, but this kind of operation are very common here, so we need to add the try catch for each handle method.

And a better way to do this is to let the exception thrown out to the application, and the application can commonly handle this kind of exception.

**Comment by apalumbo** [comment]
Taken a look in the code I've seen that the exception is only logged but not thrown again. This could be an issue or not. In this way it is supposed that am event bus handling method  must not raise exceptions, but it could be also nice to handle the exception in only one point so a common error handling could be useful.
In my opinion I would change the code so that only runtime exceptions not related on the dispatching strategy (like NoSuchMethodException) are thrown, this will enable the caller to know if something bad is happened.

**Comment by apalumbo** [comment]
Hi fbird on the pull request Mika is about to merge there is also the fix for the exception propagation, now the bus will now swallow exceptions.

Regards

Alessandro

**Comment by mtam** [comment]
Should be fixed with new version 0.9.2 with contributions from Alessandro.
